


const EMOJI_LIST = [
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "085b85f0-9a25-4acd-bc2f-2b8fe95ed5b2",
        "emojiPkg": "三角猫の日常",
        "emojiName": "三角猫の日常",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/三角猫の日常.png",
        "cid": "",
        "tags": ["日常", "喵星人", "搞笑", "呆萌"],
        "desc": "今天也是三角猫的一天喵~",
        "address": "",
        "type": "banner"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "085b85f0-9a25-4acd-bc2f-2b8fe95ed5b2",
        "emojiPkg": "三角猫の日常",
        "emojiName": "呜呜呜",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/呜呜呜.png",
        "tags": ["日常", "喵星人", "搞笑", "呆萌"],
        "desc": "今天也是三角猫的一天喵~",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "085b85f0-9a25-4acd-bc2f-2b8fe95ed5b2",
        "emojiPkg": "三角猫の日常",
        "emojiName": "喜欢你",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/喜欢你.png",
        "tags": ["日常", "喵星人", "搞笑", "呆萌"],
        "desc": "今天也是三角猫的一天喵~",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "085b85f0-9a25-4acd-bc2f-2b8fe95ed5b2",
        "emojiPkg": "三角猫の日常",
        "emojiName": "头大",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/头大.png",
        "tags": ["日常", "喵星人", "搞笑", "呆萌"],
        "desc": "今天也是三角猫的一天喵~",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "085b85f0-9a25-4acd-bc2f-2b8fe95ed5b2",
        "emojiPkg": "三角猫の日常",
        "emojiName": "好饿",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/好饿.png",
        "tags": ["日常", "喵星人", "搞笑", "呆萌"],
        "desc": "今天也是三角猫的一天喵~",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "085b85f0-9a25-4acd-bc2f-2b8fe95ed5b2",
        "emojiPkg": "三角猫の日常",
        "emojiName": "打搅啦",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/打搅啦.png",
        "tags": ["日常", "喵星人", "搞笑", "呆萌"],
        "desc": "今天也是三角猫的一天喵~",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "085b85f0-9a25-4acd-bc2f-2b8fe95ed5b2",
        "emojiPkg": "三角猫の日常",
        "emojiName": "捡垃圾",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/捡垃圾.png",
        "tags": ["日常", "喵星人", "搞笑", "呆萌"],
        "desc": "今天也是三角猫的一天喵~",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "085b85f0-9a25-4acd-bc2f-2b8fe95ed5b2",
        "emojiPkg": "三角猫の日常",
        "emojiName": "摸鱼",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/摸鱼.png",
        "tags": ["日常", "喵星人", "搞笑", "呆萌"],
        "desc": "今天也是三角猫的一天喵~",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "085b85f0-9a25-4acd-bc2f-2b8fe95ed5b2",
        "emojiPkg": "三角猫の日常",
        "emojiName": "是吗",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/是吗.png",
        "tags": ["日常", "喵星人", "搞笑", "呆萌"],
        "desc": "今天也是三角猫的一天喵~",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "085b85f0-9a25-4acd-bc2f-2b8fe95ed5b2",
        "emojiPkg": "三角猫の日常",
        "emojiName": "有这事儿",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/有这事儿.png",
        "tags": ["日常", "喵星人", "搞笑", "呆萌"],
        "desc": "今天也是三角猫的一天喵~",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "085b85f0-9a25-4acd-bc2f-2b8fe95ed5b2",
        "emojiPkg": "三角猫の日常",
        "emojiName": "来嘛",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/来嘛.png",
        "tags": ["日常", "喵星人", "搞笑", "呆萌"],
        "desc": "今天也是三角猫的一天喵~",
        "address": "",
        "type": "ho't"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "085b85f0-9a25-4acd-bc2f-2b8fe95ed5b2",
        "emojiPkg": "三角猫の日常",
        "emojiName": "没在怕",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/没在怕.png",
        "tags": ["日常", "喵星人", "搞笑", "呆萌"],
        "desc": "今天也是三角猫的一天喵~",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "085b85f0-9a25-4acd-bc2f-2b8fe95ed5b2",
        "emojiPkg": "三角猫の日常",
        "emojiName": "讨厌鬼",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/讨厌鬼.png",
        "tags": ["日常", "喵星人", "搞笑", "呆萌"],
        "desc": "今天也是三角猫的一天喵~",
        "address": "",
        "type": "hot"
    },

    // 关羽(国语)
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "不会吧",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_不会吧.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "不行了",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_不行了.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "卧槽",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_卧槽.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "吃惊",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_吃惊.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "告辞",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_告辞.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "喜欢你",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_喜欢你.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "小萌神关羽",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_小萌神关羽.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "怎么回事",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_怎么回事.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "我太难了",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_我太难了.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "拼啦",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_拼啦.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "捧在手心",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_捧在手心.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "放马过来",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_放马过来.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "溜了",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_溜了.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "牛",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_牛.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "略略略",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_略略略.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "自然",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_自然.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "9ee2d44f-3e4a-4a40-ba99-b3e15f93ec91",
        "emojiPkg": "关羽国语版",
        "emojiName": "让我静静",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/1_让我静静.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "hot"
    },

    // 关羽(粤语)
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "不会吧",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_不会吧（唔会呱）.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "不行了",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_不行了（唔得了）.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "卧槽",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_卧槽（卧顶）.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "厉害",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_厉害.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "吓死我了",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_吓死我了.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "告辞",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_告辞.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "喜欢你",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_喜欢你.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "小萌神关羽",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_小萌神关羽.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "怎么回事",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_怎么回事（你做乜柒）.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "我太难了",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_我太难了.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "拼啦",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_拼啦.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "捧在手心",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_捧在手心.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "放马过来",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_放马过来.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "溜",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_溜.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "略略略",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_略略略.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "让我静静",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_让我静静.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "d39d7c42-54bb-40d5-8557-ab2eb05e33ae",
        "emojiPkg": "关羽粤语版",
        "emojiName": "那当然",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/2_那当然（甘系啦）.png",
        "tags": ["日常", "英雄", "搞笑", "中国风"],
        "desc": "今天的关羽更萌了吗",
        "address": "",
        "type": "newest"
    },

    // 关公拜大年
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "6c7a8de1-602e-4147-bdb9-6633ec713b77",
        "emojiPkg": "关羽拜大年",
        "emojiName": "一起拜年",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/3_一起拜年.png",
        "tags": ["春节", "祝福", "中国风", "英雄"],
        "desc": "关公来家里拜年啦！",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "6c7a8de1-602e-4147-bdb9-6633ec713b77",
        "emojiPkg": "关羽拜大年",
        "emojiName": "关公拜大年",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/3_关公拜大年.png",
        "tags": ["春节", "祝福", "中国风", "英雄"],
        "desc": "关公来家里拜年啦！",
        "address": "",
        "type": "banner"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "6c7a8de1-602e-4147-bdb9-6633ec713b77",
        "emojiPkg": "关羽拜大年",
        "emojiName": "压岁钱",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/3_压岁钱.png",
        "tags": ["春节", "祝福", "中国风", "英雄"],
        "desc": "关公来家里拜年啦！",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "6c7a8de1-602e-4147-bdb9-6633ec713b77",
        "emojiPkg": "关羽拜大年",
        "emojiName": "恭喜发财",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/3_恭喜发财.png",
        "tags": ["春节", "祝福", "中国风", "英雄"],
        "desc": "关公来家里拜年啦！",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "6c7a8de1-602e-4147-bdb9-6633ec713b77",
        "emojiPkg": "关羽拜大年",
        "emojiName": "拜年",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/3_拜年.png",
        "tags": ["春节", "祝福", "中国风", "英雄"],
        "desc": "关公来家里拜年啦！",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "6c7a8de1-602e-4147-bdb9-6633ec713b77",
        "emojiPkg": "关羽拜大年",
        "emojiName": "新年快乐",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/3_新年快乐.png",
        "tags": ["春节", "祝福", "中国风", "英雄"],
        "desc": "关公来家里拜年啦！",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "6c7a8de1-602e-4147-bdb9-6633ec713b77",
        "emojiPkg": "关羽拜大年",
        "emojiName": "棒",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/3_棒.png",
        "tags": ["春节", "祝福", "中国风", "英雄"],
        "desc": "关公来家里拜年啦！",
        "address": "",
        "type": "newest"
    },
    {
        "openId": "oHJ0d5NI6xMzNjv4da2PYRVzHUs4",
        "emojiPkgId": "6c7a8de1-602e-4147-bdb9-6633ec713b77",
        "emojiPkg": "关羽拜大年",
        "emojiName": "爱你",
        "filePath": "http://q3od7o06m.bkt.clouddn.com/3_爱你.png",
        "tags": ["春节", "祝福", "中国风", "英雄"],
        "desc": "关公来家里拜年啦！",
        "address": "",
        "type": "banner"
    }
    
]

const EMOJI_TAGS = [
"卡通",
"手绘",
"线性",
"简笔",
"字段",
"搞笑",
"沙雕",
"古风",
"炫酷",
"温暖",
"呆萌",
"可爱",
"传统",
"中国风",
"小清新",
"二次元",
"节日",
"祝福",
"春节",
"情人节",
"元宵节",
"儿童节",
"圣诞节",
"汪星人",
"喵星人",
"兔子",
"松鼠",
"熊猫",
"海獭",
"萌宠",
"怪物",
"宝宝",
"大佬",
"学生",
"老板",
"英雄",
"明星",
"程序员",
"恋爱",
"吵架",
"红包",
"工作",
"学习",
"斗图",
"问候",
"日常",
"情绪",
"吐槽",
"绿色",
"文化",
"游戏"
]

module.exports.EMOJI_LIST = EMOJI_LIST;
module.exports.EMOJI_TAGS = EMOJI_TAGS;